README.md

docs: add more content to README

---

src/append/rolling_file/rolling.rs

Changes:
- Refactor the type of `rolling.State#next_date` from usize to `Option<usize>`
- `rolling.State#next_date` is 0 when rotation is Rotation::Never. 
- Using Option compared to magic number can intuitively tell developer that `next_date` is not effective.
- Move `date.unix_timestamp() as usize` inside of `next_date`
- All callers of `Rotation#next_date` convert the data to timestamp, we can convert it inside of `Rotation#next_date`
- Also, `Rotation#next_date` needs to rename to `Rotation#next_date_timestamp`

chore: optimize the magic number to Option and extract common code

---

.github/workflows/ci.yml
Cargo.toml
src/append/rolling_file/clock.rs
src/append/rolling_file/mod.rs
src/append/rolling_file/rolling.rs
src/append/rolling_file/rotation.rs

close #34 
- refactor: move Rotation into one separate module and add test for it
- The rolling file has too many code, so move Rotation into one separate module
- test: add unit tests for rolling file
- Introduce the Clock related code to test time rotation

test: add unit tests for rolling file

---

.gitignore

I checked datafusion and opendal, both of them add the `.idea` and `.vscode` to the gitignore

chore: add the .idea and .vscode to the gitignore

---

Cargo.toml
examples/json_stdio.rs
examples/rolling_file.rs
src/append/fastrace.rs
src/append/mod.rs
src/append/rolling_file/clock.rs
src/append/rolling_file/rolling.rs
src/append/rolling_file/rotation.rs
src/layout/json.rs
src/layout/text.rs

This closes https://github.com/cratesland/logforth/issues/35.
@1996fanrui if you'd like to implement something more flexible like Logback's and Log4j's PatternLayout, you can try to follow #7.

refactor: use jiff for timestamp 

---

src/filter/level.rs
src/filter/mod.rs
src/filter/target.rs

feat: add target filter

---

Cargo.toml
src/lib.rs

To build it locally:
```
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
```
Closes https://github.com/fast/logforth/issues/45

docs: show feature flag notation on docs.rs

---

src/layout/json.rs
src/layout/text.rs

perf: Optimize the Zoned::now().with_time_zone

---

.github/workflows/ci.yml
Cargo.toml
examples/env_filter.rs
src/filter/custom.rs
src/filter/env.rs
src/filter/level.rs
src/filter/mod.rs
src/filter/target.rs
src/logger.rs

feat: support env filter 

---

src/layout/text.rs

JsonLayout can still log the full file path since it's mainly for machine read and it's easy to extract the filename during the process.
TextLayout is mainly for human reading so module name + filename should be enough and the full file path _is_ noisy.

feat: revert to short filename for TextLayout

---

CHANGELOG.md
Cargo.toml
examples/journald.rs
src/append/journald/README.md
src/append/journald/field.rs
src/append/journald/memfd.rs
src/append/journald/mod.rs
src/append/mod.rs
src/append/syslog.rs

feat: support journald appender

---

Cargo.toml
src/append/syslog.rs

Reexport  BroadcastSender from https://github.com/fast/fasyslog/pull/6

feat: reexport broadcast and native_tls from fasyslog

---

CHANGELOG.md
src/layout/json.rs
src/layout/text.rs

target is usually identical to target, while target can be manually altered like `log::debug!(target: "request", "handling request")`. And target can be used in envfilter expression like `INFO,request=DEBUG`.

feat: display target instead of module_path

---

Cargo.toml

`env_filter = 0.1.0` will not compile with the follwing errors:
```
error[E0599]: no method named `try_parse` found for struct `env_filter::Builder` in the current scope
--> src/filter/env_filter.rs:194:17
|
194 |         builder.try_parse(&config).ok()?;
|                 ^^^^^^^^^
|
help: there is a method `parse` with a similar name
|
194 |         builder.parse(&config).ok()?;
|                 ~~~~~
error[E0599]: no method named `try_parse` found for struct `env_filter::Builder` in the current scope
--> src/filter/env_filter.rs:223:16
|
223 |         self.0.try_parse(filters)?;
|                ^^^^^^^^^
|
help: there is a method `parse` with a similar name
|
223 |         self.0.parse(filters)?;
|                ~~~~~
```

fix: increase min version of env_filter to 0.1.1

---

src/append/stdio.rs
tests/recursive_logging.rs

Hi! :wave:
I just cloned the source to have a look at https://github.com/rust-lang/log/issues/655 and found a few tests that wouldn't build with a plain `cargo check --all-targets`, so fixed them up.

fix: Fix up a few tests requiring features

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
src/color.rs
src/diagnostic/mod.rs
src/layout/mod.rs
src/layout/text.rs
src/lib.rs

@andylokandy @Xuanwo shall we go in this direction?

refactor: better colored feature flag

---

CHANGELOG.md
src/append/mod.rs
src/append/rolling_file/append.rs
src/append/rolling_file/mod.rs
src/append/syslog.rs

feat: blocking appender for rolling file and syslog

---

CHANGELOG.md
src/append/mod.rs
src/append/rolling_file/append.rs
src/append/rolling_file/mod.rs
src/append/syslog.rs

After a discussion with @andylokandy I realize that the blocking impl looks "premature optimization" and even unsure whether an optimization at all. Reverted.

revert: blocking rolling file and syslog appender

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
examples/google_structured_log.rs
src/layout/google_structured_log.rs
src/layout/json.rs
src/layout/mod.rs

Implements a layout for Google's structured logging format.
Uses the `log_serde` feature of `log` to encode arbitrary serializable types into the JSON payload.
Fixes #99

feat: Support Google structured logging format

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
examples/log_with_logger.rs
src/append/journald/README.md
src/append/rolling_file/rotation.rs
src/diagnostic/mod.rs
src/diagnostic/static_global.rs
src/diagnostic/thread_local.rs
src/lib.rs
src/logger/builder.rs
src/logger/log_impl.rs

This closes https://github.com/fast/logforth/issues/113

refactor!: logger builder 

---

src/diagnostic/fastrace.rs

Closes https://github.com/fast/logforth/issues/127
Related https://github.com/fast/logforth/issues/119

fix: render trace_id and span_id for FastraceDiagnostic

---

.github/workflows/ci.yml
CHANGELOG.md
src/append/opentelemetry.rs

This follows up https://github.com/fast/logforth/pull/126

chore: otel append build is now infallible

---

Cargo.toml
examples/single_file.rs
src/append/mod.rs
src/append/single_file/append.rs
src/append/single_file/mod.rs
src/append/single_file/single.rs
src/non_blocking/builder.rs
src/non_blocking/worker.rs

I'm trying to switch to logforth from log4rs and everything is looking good except for the ability to just write to a single file. My application is a short running commandline utility that can write its log to either stderr or a file. I tried using the `RollingFile` appender with a `Rotation::Never` but I have a requirement that the log file path must be able to be set explicitly and `RollingFile` [always includes the `cnt`](https://github.com/fast/logforth/blob/v0.25.0/src/append/rolling_file/rolling.rs#L216-L224). I've gated this behind a `single-file` feature similar to `rolling-file`.
This seemed like something that could be generally useful, hence the pull request.
Thanks for taking a look!

feat: Adding `SingleFile` appender

---

CHANGELOG.md
src/diagnostic/fastrace.rs
src/layout/google_cloud_logging.rs
src/layout/json.rs
src/layout/logfmt.rs
src/layout/text.rs

This closes #169.
cc @nine9ths

refactor: print timestamp in RFC 3339 format
